services:
  - type: web
    name: final-project-backend
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MYSQLHOST
        fromDatabase:
          name: railway-mysql
          property: host
      - key: MYSQLPORT
        fromDatabase:
          name: railway-mysql
          property: port
      - key: MYSQLUSER
        fromDatabase:
          name: railway-mysql
          property: username
      - key: MYSQLPASSWORD
        fromDatabase:
          name: railway-mysql
          property: password
      - key: MYSQLDATABASE
        fromDatabase:
          name: railway-mysql
          property: database
      - key: MYSQL_URL
        fromDatabase:
          name: railway-mysql
          property: connectionString
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: railway-mysql
    databaseName: ebdb
